# AWS Lambda Python base image
FROM public.ecr.aws/lambda/python:3.11

# Copy requirements file
COPY requirements.txt .

# Install Python dependencies & Mangum
# Remove cache and build tools to save space
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir mangum && \
    rm -rf /root/.cache

# Copy project files
COPY . .

# Command to run Lambda handler
CMD ["src/lambda_handler.lambda_handler"]
